############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 10

[[main]]
name = "Contact"
url = "contact/"
weight = 11
[[main]]
name="Blogs"
url="blog/"
weight=2

[[main]]
name = "Pages"
url = "#"
weight = 3
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "Tags"
  url = "tags/"
  weight = 2

  [[main]]
  parent = "Pages"
  name = "Categories"
  url = "categories/"
  weight = 3

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "About"
url = "about/"
weight = 10

[[footer]]
name = "Contact"
url = "contact/"
weight = 11

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 15
